remote_theme: pages-themes/cayman
google_analytics: G-Z42R8RP1E5
show_downloads: true
github:
  zip_url: https://github.com/albatrossir/albatrossir.github.io/releases/download/0.02/Albatross.0.02.zip
  tar_url: https://github.com/albatrossir/albatrossir.github.io/releases/download/0.02/Albatross.0.02.tar.gz
