theme: jekyll-theme-cayman
google_analytics: G-Z42R8RP1E5
show_downloads: true
github:
  zip_url: https://github.com/albatrossir/albatrossir.github.io/releases/download/0.01/Albatross_0.01.zip
  tar_url: https://github.com/albatrossir/albatrossir.github.io/releases/download/0.01/albatross_0.01.tar.gz
